### ISSUE TITLE
Subcategories are slightly broken

### ISSUE THREAD

**Issue by trinitrot0luene** [Daemonite/discourse-material-theme#3]
[example](https://anime.needs-to-s.top/55c039.png)

Subcategories don't seem to display properly- and they're missing padding between the badge-wrapper and tags underneath.

Theme is otherwise fantastic and a joy to look at, thanks so much for making this!

**Comment by amotl** [comment]
## First things first
We second @trinitrot0luene: This theme is fantastic, thanks for all the yak shaving @sesemaya !

As you [encouraged us](https://meta.discourse.org/t/daemonite-material-theme/64521/56) to report more findings, we will try to collect them here. It's really just minor things you might already have noticed.

Cheers!

----
## This issue
We can confirm this issue is still here with the most recent release.

To be more precise, this happens when using the configuration setting `category style = bullet`:
![image](https://user-images.githubusercontent.com/453543/51079811-05a12900-16cf-11e9-8da1-aa4b4ec8cdaa.png)

While bullets render nicely in the category list on the left hand side
![image](https://user-images.githubusercontent.com/453543/51079795-b955e900-16ce-11e9-9f73-6421ce94f45e.png)

... bullets displaying subcategories in the topic list on the right hand side are broken:
![image](https://user-images.githubusercontent.com/453543/51079797-ca9ef580-16ce-11e9-8cb6-0ec7200eeb47.png)

**Comment by sesemaya** [comment]
This has been fixed by 0f4b693.

Subsequent commits also fine tunes other badge styles.
